name: cpp-linter
on:
  push:
    branches: main

jobs:
  linter:
    name: lint cpp code
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: lint code
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CLANG_FORMAT: false
    
